name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env: 
            AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
            AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
            AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
            AUTH0_CUSTOM_NAMESPACE: ${{ secrets.AUTH0_CUSTOM_NAMESPACE }}
            COSMOSDB_ENDPOINT: ${{ secrets.COSMOSDB_ENDPOINT }}
            COSMOSDB_KEY: ${{ secrets.COSMOSDB_KEY }}
            COSMOSDB_DATABASE: ${{ secrets.COSMOSDB_DATABASE }}
            COSMOSDB_COLLECTION: ${{ secrets.COSMOSDB_COLLECTION }}
            TOKEN_FOR_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_ROCK_09B561F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          production_branch: "main"
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_ROCK_09B561F03 }}
          action: "close"
